version: "3"

services:
  users:
    container_name: users
    build: .
    image: users:latest
    command: gunicorn -w 3 app:app -b 0.0.0.0:8080
    restart: always
    ports:
      - "80:8080"
    environment:
      - TEAM_NAME=CC_0193_0924_1085