version: "3"

services:
  rides:
    container_name: rides
    build: ./Rides
    image: rides:latest
    command: gunicorn -w 3 rides:app -b 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    environment:
      - TEAM_NAME=CC_0193_0924_1085

  users:
    container_name: users
    build: ./Users
    image: users:latest
    command: gunicorn -w 3 users:app -b 0.0.0.0:8080
    restart: always
    ports:
      - "8080:8080"
    environment:
      - TEAM_NAME=CC_0193_0924_1085